### ISSUE TITLE
animations disappear and reappear when using 2 animations - bad state no element

### ISSUE THREAD

**Issue by mslalith** [xvrh/lottie-flutter#55] opened 2020-05-02 15:23 UTC
I'm using Lottie animations in `CustomScrollView`. When I use single animation it's working fine but when using 2 animations, they are disappearing and reappearing.

**Error:**
`════════ Exception caught by rendering library
════════════════════════════════════════
Bad state: No element
The relevant error-causing widget was Container
════════════════════════════════════════`

**my 2nd Lottie animation:**
`return SliverToBoxAdapter(
        child: Container(
        height: 180.0,
        child: Lottie.asset(ANIMATION_LOADING_DATA),
    ),
);`

**Comment by xvrh** [comment] 2020-05-03 12:55
Hi,
Thanks for the report.
I'm not familiar with the `CustomScrollView` widget. Could you post a small reproduction of your problem so I can reproduce it locally?

Thanks.

**Comment by mslalith** [comment] 2020-05-12 07:26
when I use the same Lottie file for multiple times, it doesn't cause an error.
```
CustomScrollView(
    slivers: <Widget>[
        SliverToBoxAdapter(
            child: Container(
                height: 180.0,
                child: Lottie.asset('assets/loading.json'),
            ),
        ),
        SliverToBoxAdapter(
            child: Container(
                height: 180.0,
                child: Lottie.asset('assets/loading.json'),
            ),
        ),
    ],
);
```
but when I use different Lottie files, it crashes saying `state: No element The relevant error-causing widget was Container`.
```
CustomScrollView(
    slivers: <Widget>[
        SliverToBoxAdapter(
            child: Container(
                height: 180.0,
                child: Lottie.asset('assets/loading.json'),
            ),
        ),
        SliverToBoxAdapter(
            child: Container(
                height: 180.0,
                child: Lottie.asset('assets/shoot.json'),
            ),
        ),
    ],
);
```

**Comment by xvrh** [comment] 2020-05-12 19:00
I tried this program, but I'm not able to reproduce the error you have.

```dart
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  const App({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            for (var i = 0; i < 10; i++)
              SliverToBoxAdapter(
                child: Container(
                  height: 180.0,
                  child: Lottie.asset('assets/AndroidWave.json'),
                ),
              ),
          ],
        ),
      ),
    );
  }
}
```

Can you paste here (or provide a link) a fully executable version of your code? 

Thanks.

**Comment by mslalith** [comment] 2020-05-14 16:15
Instead of using same Lottie file, run using different Lottie files

**Comment by xvrh** [comment] 2020-05-14 16:22
Oh sorry, I miss read the problem.
But even with different files I'm not able to reproduce it. Can you provide a standalone program? Maybe also with your json files?
What version of Flutter do you use?

Thanks.

**Comment by xvrh** [comment] 2020-12-12 21:48
I'll close it since it's not actionable without a simple reproducible program.

**Closed by xvrh** 2020-12-12 21:48 UTC
