### ISSUE TITLE
Wrong size on profile mode

### ISSUE THREAD

**Issue by ThomasEcalle** [xvrh/lottie-flutter#188] opened 2021-12-07 16:09 UTC
Hi !

First of all, thank you for the awesome package and for the Flutter integration !

### The issue

I have an issue when running my app on **profile** mode.

When running on profile mode, at first, sizes and proportions seem OK.

But, after quitting the app and re-launching it, my animation size is wrong.

### Flutter doctor

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2018.2.7)
[✓] VS Code (version 1.52.1)
[✓] VS Code (version 1.27.2)
[✓] Connected device (3 available)

• No issues found!`

### Description

Here you can see 2 screens (first launch and second).
In order to be able to compare, I have added an other animation picked up randomly in your example.

As you can see, mine has a wrong size on second launch but not yours.
My lottie animation uses PNG, may be that is the issue ?

That raises 2 questions :

* why does it appear only on **profile** mode and not in debug ?
* if it is not due to PNG usage, what is the problem ?

<img src="https://user-images.githubusercontent.com/15629864/145061829-35b38bbe-1743-4cc0-88ca-785615b73d66.jpg" alt="Screenshot_20211207-163253" width="200"/>

<img src="https://user-images.githubusercontent.com/15629864/145063696-28ba29da-44b6-4575-ab09-ad9336e2516b.jpg" alt="Screenshot_20211207-163300" width="200"/>

Thank you in advance for your help and advices !

**Comment by moNiti** [comment] 2021-12-13 05:24
Same problem here. T_T

**Comment by Willian0liveira** [comment] 2021-12-15 03:26
estou tendo o mesmo problema

**Comment by design2be** [comment] 2022-06-07 14:33
We have the same issue on OSX.

It can be reproduced by the following steps:
1.  Start app on Retina Display 
2. Move window to non Retina Display
3. Render Lottie  -> Lottie is being rendered smaller than original size. 

This can be done the other way around as well. 

1.  Start app on Non Retina Display 
2. Move window to Retina Display
3. Render Lottie  -> Lottie is being rendered bigger than original size. 

This seems to be due to saving the screen size on app launch for this plugin which no longer updates.

**Comment by xvrh** [comment] 2022-06-07 14:41
@design2be 
> This seems to be due to saving the screen size on app launch for this plugin which no longer updates.

Yes, the parser relies on `window.devicePixelRatio` at several places (ie. https://github.com/xvrh/lottie-flutter/blob/master/lib/src/parser/lottie_composition_parser.dart#L32)

This has caused other issues like: https://github.com/xvrh/lottie-flutter/issues/216

It would be great to remove this usage from the parser and instead dynamically compute the correct size during the rendering. PR in this direction are more than welcome.

**Comment by xvrh** [comment] 2022-12-17 20:39
This issue should be fixed with the release v2.0.0

**Closed by xvrh** 2022-12-17 20:39 UTC
Labels: help wanted
